name: okyyds_yyds
on:
  schedule:
    - cron: '1 4 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: okyyds_yyds
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync okyyds_yyds
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/okyyds/yyds.git"
          source_branch: "master"
          destination_branch: "okyyds_yyds"
          github_token: ${{ secrets.PAT }}
